### ISSUE TITLE
2019 To-Do

### ISSUE THREAD

**Issue by swanson** [swanson/slotback-labs#1]
- [ ] Get a CSV dump for GLSP
- [ ] Backfill API data from past seasons
- [ ] Improve boxscores and add for positions other than WR
- [ ] Set up article template
